### ISSUE TITLE
Calling toString() or the __string metamethod throws an exception

### ISSUE THREAD

**Issue by clarajk** [SirTony/Mond.BindingEx#1]
For some reason, calling `toString()` or the `__string` metamethod on an instance of a class binding throws a `NotSupportedException`, yet the bound .NET `ToString()` works properly.

``` csharp
var code = @"
    var bigInt = BigInteger.new( 100 );
    printLn( bigInt.ToString() ); // OK; prints '100'
    printLn( bigInt );            // error
    printLn( bigInt.toString() ); // error
";

var options = new MondCompilerOptions { UseImplicitGlobals = true };
var program = MondProgram.Compile( code );
var state = new MondState();

MondObjectBinder.Bind<BigInteger>( state, MondBindingOptions.AutoLock | MondBindingOptions.AutoInsert );

state.Load( program );
```

**Comment by Rohansi** [comment]
This was fixed in https://github.com/Rohansi/Mond/commit/e5f01c02c8576b9e75d335993c48deef9f0a91b3. I will update the NuGet package soon so you can use it here.

You will also need to remove the instance parameter passed to `__string` and the other conversion metamethods to get that example to work.
